name: kurtosis-pre-run
description: Prepare the environment for deploying kurtosis packages

inputs:
  docker_username:
    description: The username for Docker Hub
    required: true
  docker_token:
    description: The token for Docker Hub
    required: true

  # tool versions
  kurtosis_version:
    description: Version of kurtosis to install
    default: "1.13.2"
  foundry_version:
    description: Version of foundry to install
    default: "1.5.0"
  polycli_version:
    description: Version of polygon-cli to install
    default: "0.1.97"
  python_version:
    description: Version of python to install
    default: "3.13"

runs:
  using: composite
  steps:
    - name: Free up disk space
      if: ${{ !env.ACT }}
      uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: false
        docker-images: true
        swap-storage: true

    # Install dependencies
    - name: Install kurtosis
      shell: bash
      run: |
        echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
        sudo apt update
        sudo apt install -y kurtosis-cli=${{ inputs.kurtosis_version }}
        kurtosis analytics disable
        kurtosis version
    
    - name: Install python
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install jq
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y jq
        jq --version

    - name: Install yq
      shell: bash
      run: |
        pip3 install yq
        yq --version

    - name: Install foundry
      uses: foundry-rs/foundry-toolchain@50d5a8956f2e319df19e6b57539d7e2acb9f8c1e # v1.5.0
      with:
        version: v${{ inputs.foundry_version }}
        cache: false
    
    - name: Install bats
      uses: bats-core/bats-action@42fcc8700f773c075a16a90eb11674c0318ad507 # 3.0.1
      with:
        support-path: ${{ github.workspace }}/lib/bats-support
        assert-path: ${{ github.workspace }}/lib/bats-assert
        detik-path: ${{ github.workspace }}/lib/bats-detik
        file-path: ${{ github.workspace }}/lib/bats-file

    - name: Install polycli
      shell: bash
      run: |
        polycli_version="v${{ inputs.polycli_version }}"
        pushd $(mktemp -d) || exit 1
        curl -s -L "https://github.com/0xPolygon/polygon-cli/releases/download/${polycli_version}/polycli_${polycli_version}_linux_amd64.tar.gz" > polycli.tar.gz
        tar xf polycli.tar.gz
        mv polycli_* /usr/local/bin/polycli
        polycli version

    # Login to registries
    - name: Login to docker registry
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_token }}

    - name: Login to github container registry
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Log in to GCR
      if: ${{ !env.ACT }}
      uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
      with:
        workload_identity_provider: projects/337907489413/locations/global/workloadIdentityPools/github-wif/providers/github
        service_account: testing-hub-ci@prj-polygonlabs-devtools-dev.iam.gserviceaccount.com

    - name: Configure Docker to use GCR
      if: ${{ !env.ACT }}
      shell: bash
      run: gcloud auth configure-docker europe-west2-docker.pkg.dev

    # Pull images from GCR if specified
    - uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Add registry prefix to image names
      shell: bash
      working-directory: .github/scripts
      run: python3 add-registry-prefix.py \
        --registry-prefix "europe-west2-docker.pkg.dev/prj-polygonlabs-devtools-dev/virtual" \
        --input-file "src/package_io/constants.star"
