name: cron

on:
  schedule:
    - cron: "0 0 * * *" # Run every day at 00:00 UTC.
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  kurtosis-cdk-op-geth:
    strategy:
      fail-fast: false
      matrix:
        include:
          - stack_type: rollup
          - stack_type: sovereign-pessimistic # old sovereign environment
          - stack_type: sovereign-ecdsa-multisig # new sovereign environment
    secrets: inherit
    uses: ./.github/workflows/kurtosis-cdk-op-geth.yml
    with:
      stack_type: ${{ matrix.stack_type }}
      environment_duration_seconds: "60" # 1min for now

  kurtosis-cdk-erigon:
    strategy:
      fail-fast: false
      matrix:
        include:
          - stack_type: rollup
          - stack_type: validium
          - stack_type: sovereign-pessimistic # old sovereign environment
          - stack_type: sovereign-ecdsa-multisig # new sovereign environment
    secrets: inherit
    uses: ./.github/workflows/kurtosis-cdk-erigon.yml
    with:
      stack_type: ${{ matrix.stack_type }}
      environment_duration_seconds: "60" # 1min for now
