name: kurtosis-pos

on:
  workflow_call:
    inputs:
      # Component versions
      kurtosis_pos_package_version:
        type: string
        default: "1.2.6"
      heimdall_v2_version:
        type: string
        default: "0.5.3"
      bor_version:
        type: string
        default: "2.5.5"
      erigon_version:
        type: string
        default: "3.3.0"

      # Test environment configuration
      test_duration_minutes:
        description: how long to keep the test environment running (in minutes)
        type: string
        default: 60

  workflow_dispatch:
    inputs:
      # Component versions
      kurtosis_pos_package_version:
        type: string
        default: "1.2.5"
      heimdall_v2_version:
        type: string
        default: "0.5.3"
      bor_version:
        type: string
        default: "2.5.5"
      erigon_version:
        type: string
        default: "3.3.0"

      # Test environment configuration
      test_duration_minutes:
        description: How long to keep the test environment running (in minutes)
        type: string
        default: 60

env:
  SLACK_CHANNEL_ID: C09UY6RJ38U

permissions:
  contents: read
  actions: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v6

      - name: Prepare environment
        uses: ./.github/actions/kurtosis-pre-run
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_token: ${{ secrets.DOCKER_TOKEN }}
          kurtosis_package_type: kurtosis-pos
          kurtosis_package_version: ${{ inputs.kurtosis_pos_package_version }}

      - name: Customize args file
        run: |
          args_file="${{ github.workspace }}/kurtosis-pos/.github/configs/rio.yml"
          echo "Using args file: ${args_file}"
          echo "ARGS_FILE=${args_file}" >> "${GITHUB_ENV}"

          # Customize component versions
          if [[ "${{ inputs.heimdall_v2_version }}" ]]; then
            yq --yaml-roundtrip --in-place ".polygon_pos_package.participants[0].cl_image = \"0xpolygon/heimdall-v2:${{ inputs.heimdall_v2_version }}\"" ${args_file}
            yq --yaml-roundtrip --in-place ".polygon_pos_package.participants[1].cl_image = \"0xpolygon/heimdall-v2:${{ inputs.heimdall_v2_version }}\"" ${args_file}
            yq --yaml-roundtrip --in-place ".polygon_pos_package.participants[2].cl_image = \"0xpolygon/heimdall-v2:${{ inputs.heimdall_v2_version }}\"" ${args_file}
            yq --yaml-roundtrip --in-place ".polygon_pos_package.participants[3].cl_image = \"0xpolygon/heimdall-v2:${{ inputs.heimdall_v2_version }}\"" ${args_file}
            yq --yaml-roundtrip --in-place ".polygon_pos_package.participants[4].cl_image = \"0xpolygon/heimdall-v2:${{ inputs.heimdall_v2_version }}\"" ${args_file}
          fi

          if [[ "${{ inputs.bor_version }}" ]]; then
            yq --yaml-roundtrip --in-place ".polygon_pos_package.participants[0].el_image = \"0xpolygon/bor:${{ inputs.bor_version }}\"" ${args_file}
            yq --yaml-roundtrip --in-place ".polygon_pos_package.participants[1].el_image = \"0xpolygon/bor:${{ inputs.bor_version }}\"" ${args_file}
            yq --yaml-roundtrip --in-place ".polygon_pos_package.participants[2].el_image = \"0xpolygon/bor:${{ inputs.bor_version }}\"" ${args_file}
            yq --yaml-roundtrip --in-place ".polygon_pos_package.participants[4].el_image = \"0xpolygon/bor:${{ inputs.bor_version }}\"" ${args_file}
          fi

          if [[ "${{ inputs.erigon_version }}" ]]; then
            yq --yaml-roundtrip --in-place ".polygon_pos_package.participants[3].el_image = \"0xpolygon/erigon:v${{ inputs.erigon_version }}\"" ${args_file}
          fi

          # Start spammer services
          yq --yaml-roundtrip --in-place '.polygon_pos_package.additional_services += ["tx_spammer", "bridge_spammer", "status_checker"]' ${args_file}

          # Display the customized args file
          cat ${args_file}

      - name: Deploy enclave
        working-directory: kurtosis-pos
        run: |
          enclave_name="kurtosis-pos"
          echo "ENCLAVE_NAME=${enclave_name}" >> "${GITHUB_ENV}"
          echo "ENCLAVE_NAME=${enclave_name}"
          kurtosis run --enclave $enclave_name --args-file ${{ env.ARGS_FILE }} .

      - name: Inspect enclave
        run: kurtosis enclave inspect ${{ env.ENCLAVE_NAME }}

      - name: Monitor system
        working-directory: .github/scripts
        run: ./idle.sh ${{ inputs.test_duration_minutes }}

      - name: Collect logs and enclave state
        if: always()
        uses: ./.github/actions/kurtosis-post-run
        with:
          enclave_name: ${{ env.ENCLAVE_NAME }}

  slack:
    runs-on: ubuntu-latest
    if: always()
    needs: test
    steps:
      - uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        with:
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          method: chat.postMessage
          payload: |
            {
              "channel": ${{ env.SLACK_CHANNEL_ID }},
              "text": "Testing Hub Nightly - Test Summary",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Testing Hub Nightly: ${{ contains(needs.*.result, 'failure') && 'some tests failed ❌' || (contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped')) && 'some tests were skipped ⚠️' || 'all tests passed ✅' }}\n- environment: kurtosis-pos\n- duration: ${{ inputs.test_duration_minutes }} minutes\n- <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|explore logs>"
                  }
                }
              ]
            }
