name: kurtosis-cdk-erigon

on:
  workflow_call:
    inputs:
      # Stack deployment configuration
      stack_type:
        description: Type of cdk-erigon stack to deploy
        type: string
        default: rollup # mock-prover

      # Component versions
      kurtosis_cdk_package_version:
        type: string
        default: "0.5.11"
      aggkit_version:
        description: only for sovereign type
        type: string
        default: "0.7.2"
      aggkit_prover_version:
        description: only for rollup type
        type: string
        default: "1.8.0"
      agglayer_version:
        type: string
        default: "0.4.4"
      agglayer_contracts_version:
        type: string
        default: "12.1.6-fork.0"
      cdk_erigon_version:
        type: string
        default: "2.64.0-RC10"
      cdk_node_version:
        description: only for rollup and validium types
        type: string
        default: "0.5.4"
      zkevm_bridge_service_version:
        type: string
        default: "0.6.3-RC7"
      zkevm_data_availability_version:
        description: only for validium type
        type: string
        default: "0.0.13"
      zkevm_pool_manager_version:
        type: string
        default: "0.1.3"
      zkevm_prover_version:
        description: only for rollup and validium types
        type: string
        default: "8.0.0-RC16"

      # Test environment configuration
      environment_duration_seconds:
        description: How long to keep the test environment running (in seconds)
        type: string
        default: "120" # 2min for now

  workflow_dispatch:
    inputs:
      # Stack deployment configuration
      stack_type:
        description: Type of cdk-erigon stack to deploy
        type: choice
        options:
          - rollup # mock prover
          - validium
          - sovereign-pessimistic # old sovereign environment
          - sovereign-ecdsa-multisig # new sovereign environment
        default: rollup

      # Component versions
      kurtosis_cdk_package_version:
        type: string
        default: "0.5.11"
      aggkit_version:
        description: only for sovereign type
        type: string
        default: "0.7.2"
      aggkit_prover_version:
        description: only for rollup type
        type: string
        default: "1.8.0"
      agglayer_version:
        type: string
        default: "0.4.4"
      agglayer_contracts_version:
        type: string
        default: "12.1.6-fork.0"
      cdk_erigon_version:
        type: string
        default: "2.64.0-RC10"
      cdk_node_version:
        description: only for rollup and validium types
        type: string
        default: "0.5.4"
      zkevm_bridge_service_version:
        type: string
        default: "0.6.3-RC7"
      zkevm_data_availability_version:
        description: only for validium type
        type: string
        default: "0.0.13"
      zkevm_pool_manager_version:
        type: string
        default: "0.1.3"
      zkevm_prover_version:
        description: only for rollup and validium types
        type: string
        default: "8.0.0-RC16-fork.12"

      # Test environment configuration
      environment_duration_seconds:
        description: How long to keep the test environment running (in seconds)
        type: string
        default: "120" # 2min for now

env:
  SLACK_CHANNEL_ID: C09UY6RJ38U

permissions:
  contents: read
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v6

      - name: Prepare environment
        uses: ./.github/actions/kurtosis-pre-run
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_token: ${{ secrets.DOCKER_TOKEN }}

      - name: Clone 0xPolygon/kurtosis-cdk
        uses: actions/checkout@v6
        with:
          repository: 0xPolygon/kurtosis-cdk
          ref: v${{ inputs.kurtosis_cdk_package_version }}
          path: kurtosis-cdk

      - name: Customize args file
        run: |
          # Select args file based on stack type
          args_file="${{ github.workspace }}/kurtosis-cdk/.github/tests/cdk-erigon/"
          if [[ "${{ inputs.stack_type }}" == "rollup" ]]; then
            args_file+="rollup.yml"
          elif [[ "${{ inputs.stack_type }}" == "sovereign-pessimistic" ]]; then
            args_file+="sovereign-pessimistic.yml"
          elif [[ "${{ inputs.stack_type }}" == "sovereign-ecdsa-multisig" ]]; then
            args_file+="sovereign-ecdsa-multisig.yml"
          elif [[ "${{ inputs.stack_type }}" == "validium" ]]; then
            args_file+="validium.yml"
          else
            echo "Unknown stack type: ${{ inputs.stack_type }}"
            exit 1
          fi
          echo "Using args file: ${args_file}"
          echo "ARGS_FILE=${args_file}" >> "${GITHUB_ENV}"

          # Customize component versions
          if [[ "${{ inputs.aggkit_version }}" ]]; then
            yq --yaml-roundtrip --in-place ".args.aggkit_image = \"ghcr.io/agglayer/aggkit:${{ inputs.aggkit_version }}\"" ${args_file}
          fi

          if [[ "${{ inputs.aggkit_prover_version }}" ]]; then
            yq --yaml-roundtrip --in-place ".args.aggkit_prover_image = \"ghcr.io/agglayer/aggkit-prover:${{ inputs.aggkit_prover_version }}\"" ${args_file}
          fi

          if [[ "${{ inputs.agglayer_version }}" ]]; then
            yq --yaml-roundtrip --in-place ".args.agglayer_image = \"ghcr.io/agglayer/agglayer:${{ inputs.agglayer_version }}\"" ${args_file}
          fi

          if [[ "${{ inputs.agglayer_contracts_version }}" ]]; then
            yq --yaml-roundtrip --in-place ".args.agglayer_contracts_image = \"europe-west2-docker.pkg.dev/prj-polygonlabs-devtools-dev/public/agglayer-contracts:v${{ inputs.agglayer_contracts_version }}\"" ${args_file}
          fi

          if [[ "${{ inputs.cdk_erigon_version }}" ]]; then
            yq --yaml-roundtrip --in-place ".args.cdk_erigon_node_image = \"hermeznetwork/cdk-erigon:v${{ inputs.cdk_erigon_version }}\"" ${args_file}
          fi

          if [[ "${{ inputs.cdk_node_version }}" ]]; then
            yq --yaml-roundtrip --in-place ".args.cdk_node_image = \"ghcr.io/0xpolygon/cdk:${{ inputs.cdk_node_version }}\"" ${args_file}
          fi

          if [[ "${{ inputs.zkevm_bridge_service_version }}" ]]; then
            yq --yaml-roundtrip --in-place ".args.zkevm_bridge_service_image = \"ghcr.io/0xpolygon/zkevm-bridge-service:v${{ inputs.zkevm_bridge_service_version }}\"" ${args_file}
          fi

          if [[ "${{ inputs.zkevm_data_availability_version }}" ]]; then
            yq --yaml-roundtrip --in-place ".args.zkevm_da_image = \"ghcr.io/0xpolygon/cdk-data-availability:${{ inputs.zkevm_data_availability_version }}\"" ${args_file}
          fi

          if [[ "${{ inputs.zkevm_pool_manager_version }}" ]]; then
            yq --yaml-roundtrip --in-place ".args.zkevm_bridge_service_image = \"ghcr.io/0xpolygon/zkevm-pool-manager:${{ inputs.zkevm_pool_manager_version }}\"" ${args_file}
          fi

          if [[ "${{ inputs.zkevm_prover_version }}" ]]; then
            yq --yaml-roundtrip --in-place ".args.zkevm_bridge_service_image = \"hermeznetwork/zkevm-prover:v${{ inputs.zkevm_prover_version }}\"" ${args_file}
          fi

          # Display the customized args file
          cat ${args_file}

      - name: Deploy enclave
        working-directory: kurtosis-cdk
        run: |
          enclave_name="kurtosis-cdk-erigon-${{ inputs.stack_type }}"
          echo "ENCLAVE_NAME=${enclave_name}" >> "${GITHUB_ENV}"
          echo "ENCLAVE_NAME=${enclave_name}"
          kurtosis run --enclave $enclave_name --args-file ${{ env.ARGS_FILE }} .

      - name: Inspect enclave
        run: kurtosis enclave inspect ${{ env.ENCLAVE_NAME }}

      - name: Monitor system
        working-directory: .github/scripts
        run: ./idle.sh ${{ inputs.environment_duration_seconds }}

      - name: Collect logs and enclave state
        if: always()
        uses: ./.github/actions/kurtosis-post-run
        with:
          enclave_name: ${{ env.ENCLAVE_NAME }}

      - name: Report to slack
        if: always()
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        with:
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          method: chat.postMessage
          payload: |
            {
              "channel": ${{ env.SLACK_CHANNEL_ID }},
              "text": "Test Summary: kurtosis-cdk-erigon",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "kurtosis-cdk-erigon: ${{ contains(needs.*.result, 'failure') && 'some tests failed ❌' || (contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped')) && 'some tests were skipped ⚠️' || 'all tests passed ✅' }}",
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Links:*\n- <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Workflow Run>"
                  }
                }
              ]
            }
