name: kurtosis-cdk-op-geth

on:
  workflow_dispatch:
    inputs:
      # Stack type
      type:
        description: Type of Polygon CDK op-geth stack to deploy
        type: choice
        options:
          - rollup # mock prover
          - sovereign
          - aggchain-ecdsa-multisig
        default: rollup

      # Component versions
      aggkit_version:
        description: aggkit version to use
        type: string
        default: "0.7.2"
      aggkit_prover_version:
        description: aggkit-prover version to use (only for rollup type)
        type: string
        default: "1.8.0"
      agglayer_version:
        description: agglayer version to use
        type: string
        default: "0.4.4"
      op_geth_version:
        description: op-geth version to use
        type: string
        default: "1.101603.5"
      op_node_version:
        description: op-node version to use
        type: string
        default: "1.16.2"
      op_batcher_version:
        description: op-batcher version to use
        type: string
        default: "1.16.2"
      op_proposer_version:
        description: op-proposer version to use (only for sovereign type)
        type: string
      op_succinct_proposer_version:
        description: op-succinct-proposer version to use (only for rollup type)
        type: string
        default: "3.4.0-rc.1-agglayer"
      zkevm_bridge_service_version:
        description: zkevm-bridge-service version to use
        type: string
        default: "0.6.3-RC7"

      # Package and test versions
      kurtosis_package_version:
        description: Version of the Kurtosis package to use
        type: string
        default: "0.5.9"
      e2e_test_version:
        description: Version of the e2e test package to use
        type: string
        default: "6a06f5b"
      e2e_test_tags:
        description: Tags to use for the e2e test package
        type: string
        default: "bridge"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Pre kurtosis run
        uses: ./.github/actions/kurtosis-pre-run
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_token: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Generate enclave name
        run: |
          enclave_name="kurtosis-cdk-op-geth-${{ inputs.type }}"
          echo "ENCLAVE_NAME=${enclave_name}" >> "${GITHUB_ENV}"
          echo "ENCLAVE_NAME=${enclave_name}"

      - name: Clone 0xPolygon/kurtosis-cdk repository
        uses: actions/checkout@v6
        with:
          repository: 0xPolygon/kurtosis-cdk
          ref: v${{ inputs.kurtosis_package_version }}
          path: kurtosis-cdk

      - name: Customize args file
        run: |
          # Select args file based on stack type
          args_file="${{ github.workspace }}/kurtosis-cdk/.github/tests/"
          if [[ "${{ inputs.type }}" == "rollup" ]]; then
            args_file+="op-succinct/mock-prover.yml"
          elif [[ "${{ inputs.type }}" == "sovereign" ]]; then
            args_file+="op-geth/sovereign.yml"
          elif [[ "${{ inputs.type }}" == "aggchain-ecdsa-multisig" ]]; then
            args_file+="op-geth/aggchain-ecdsa-multisig.yml"
          else
            echo "Unknown stack type: ${{ inputs.type }}"
            exit 1
          fi
          echo "Using args file: ${args_file}"
          echo "ARGS_FILE=${args_file}" >> "${GITHUB_ENV}"

          # Customize component versions
          if [[ "${{ inputs.aggkit_version }}" ]]; then
            yq --yaml-roundtrip --in-place ".args.aggkit_image = \"ghcr.io/agglayer/aggkit:${{ inputs.aggkit_version }}\"" ${args_file}
          fi
          if [[ "${{ inputs.aggkit_prover_version }}" ]]; then
            yq --yaml-roundtrip --in-place ".args.aggkit_prover_image = \"ghcr.io/agglayer/aggkit-prover:${{ inputs.aggkit_prover_version }}\"" ${args_file}
          fi
          if [[ "${{ inputs.agglayer_version }}" ]]; then
            yq --yaml-roundtrip --in-place ".args.agglayer_image = \"ghcr.io/agglayer/agglayer:${{ inputs.agglayer_version }}\"" ${args_file}
          fi
          if [[ "${{ inputs.op_geth_version }}" ]]; then
            yq --yaml-roundtrip --in-place ".args.op_geth_image = \"us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v${{ inputs.op_geth_version }}\"" ${args_file}
          fi
          if [[ "${{ inputs.op_node_version }}" ]]; then
            yq --yaml-roundtrip --in-place ".args.op_node_image = \"us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v${{ inputs.op_node_version }}\"" ${args_file}
          fi
          if [[ "${{ inputs.op_batcher_version }}" ]]; then
            yq --yaml-roundtrip --in-place ".args.op_batcher_image = \"us-docker.pkg.dev/oplabs-tools-artifacts/images/op-batcher:v${{ inputs.op_batcher_version }}\"" ${args_file}
          fi
          if [[ "${{ inputs.op_proposer_version }}" ]]; then
            if [[ "${{ inputs.type }}" == "sovereign" ]]; then
              yq --yaml-roundtrip --in-place ".args.op_proposer_image = \"us-docker.pkg.dev/oplabs-tools-artifacts/images/op-proposer:v${{ inputs.op_proposer_version }}\"" ${args_file}
            else
              echo "op_proposer_version is only applicable for 'sovereign' type"
              exit 1
            fi
          fi
          if [[ "${{ inputs.op_succinct_proposer_version }}" ]]; then
            if [[ "${{ inputs.type }}" == "rollup" ]]; then
              yq --yaml-roundtrip --in-place ".args.op_succinct_proposer_image = \"ghcr.io/agglayer/op-succinct/op-succinct-agglayer:v${{ inputs.op_succinct_proposer_version }}\"" ${args_file}
            else
              echo "op_succinct_proposer_version is only applicable for 'rollup' type"
              exit 1
            fi
          fi
          if [[ "${{ inputs.zkevm_bridge_service_version }}" ]]; then
            yq --yaml-roundtrip --in-place ".args.zkevm_bridge_service_image = \"ghcr.io/0xpolygon/zkevm-bridge-service:v${{ inputs.zkevm_bridge_service_version }}\"" ${args_file}
          fi

          # Display the customized args file
          yq . ${args_file}

      - name: Kurtosis run
        working-directory: kurtosis-cdk
        run: kurtosis run --enclave=${{ env.ENCLAVE_NAME }} --args-file ${{ env.ARGS_FILE }} github.com/0xPolygon/kurtosis-cdk@v${{ inputs.kurtosis_package_version }}

      - name: Monitor rollup
        working-directory: .github/actions/kurtosis-post-run
        run: |
          l2_rpc_service_name="op-el-1-op-geth-op-node-001"
          export RPC_URL=$(kurtosis port print ${{ env.ENCLAVE_NAME }} ${l2_rpc_service_name} rpc)
          ./monitor.sh
      
      - name: Clone agglayer/e2e repository
        uses: actions/checkout@v6
        with:
          repository: agglayer/e2e
          ref: ${{ inputs.e2e_test_version }}

      - name: Run e2e tests
        working-directory: e2e
        run: |
          set -a
          source ./tests/.env
          set +a
          export BATS_LIB_PATH="$PWD/core/helpers/lib"
          export PROJECT_ROOT="$PWD"
          export ENCLAVE_NAME="${{ env.ENCLAVE_NAME }}"
          bats --filter-tags ${{ inputs.e2e_test_flags }} .

      - name: Post kurtosis run
        if: always()
        uses: ./.github/actions/kurtosis-post-run
        with:
          enclave_name: ${{ env.ENCLAVE_NAME }}
